Repository ripe-tech/ripe-sdk, pull requests merged in 2020-11, with the labels that each got.

#208 Avoid extra network requests on initial updates
  src/js/base/ripe.js
  src/js/visual/configurator-prc.js
Labels: enhancement

#209 Add getMesh
  src/js/api/brand.js
Labels: enhancement

#210 getMeshUrl
  src/js/api/brand.js
Labels: enhancement, fast-track

#212 #211: getLogo and getLogoP methods
  src/js/api/brand.js
  test/js/api/brand.js
Labels: enhancement

#213 #172 Support for more image options
  src/js/base/api.js
  src/js/visual/image.js
Labels: enhancement

#214 Use node_modules dependencies
  gulpfile.js
  package.json
  src/python/ripe_demo/templates/partials/layout.html.tpl
Labels: enhancement, talk

#217 Fixed rotation initialization
  src/js/visual/image.js
Labels: bug

#215 #172 Image options test
  src/js/base/api.js
  test/js/visual.js
Labels: bug, unit-testing

#216 #67 Add availability rules methods to access endpoints
  src/js/api/availability-rule.js
  src/js/api/index.js
Labels: enhancement

#218 #677: on_part not respected
  package.json
  src/js/api/account.js
  src/js/api/availability-rule.js
  src/js/api/brand.js
  src/js/api/build.js
  src/js/api/config.js
  src/js/api/country-group.js
  src/js/api/justification.js
  src/js/api/letter-rule.js
  src/js/api/locale.js
  src/js/api/notify-info.js
  src/js/api/oauth.js
  src/js/api/order.js
  src/js/api/price-rule.js
  src/js/api/profile.js
  src/js/api/size.js
  src/js/api/sku.js
  src/js/base/api.js
  src/js/base/auth.js
  src/js/base/base.js
  src/js/base/compat.js
  src/js/base/config.js
  src/js/base/errors.js
  src/js/base/interactable.js
  src/js/base/logic.js
  src/js/base/mobile.js
  src/js/base/observable.js
  src/js/base/ripe.js
  src/js/base/utils.js
  src/js/plugins/base.js
  src/js/plugins/diag.js
  src/js/plugins/restrictions.js
  src/js/plugins/sync.js
  src/js/visual/configurator-prc.js
  src/js/visual/configurator.js
  src/js/visual/image.js
  src/js/visual/visual.js
Labels: bug

#219 #172 Added missing params
  src/js/base/api.js
Labels: bug

#222 Switched isEmpty method call
  src/js/base/ripe.js
Labels: bug
