Repository ripe-tech/ripe-sdk, pull requests merged in 2020-12, with the labels that each got.

#223 Update links to docs
  src/js/api/brand.js
Labels: enhancement

#224 Brand getLogic endpoints
  src/js/api/brand.js
  test/js/api/brand.js
Labels: enhancement

#225 #618 Add validate model method
  src/js/api/brand.js
  src/js/base/api.js
Labels: enhancement

#228 DataJ problem in _runLogicOptions
  src/js/api/brand.js
  test/js/api/brand.js
Labels: bug, unit-testing

#230 Add missing params to configInfo
  src/js/api/config.js
Labels: enhancement

#227 #45: Configurator error on destroy
  src/js/visual/configurator-prc.js
  src/js/visual/image.js
Labels: bug
