Repository ripe-tech/ripe-sdk, pull requests merged in 2020-06, with the labels that each got.

#173 #349: onLogic enpoint
  src/js/api/brand.js
Labels: enhancement

#178 Fix authentication with key
  src/js/base/api.js
  src/js/base/auth.js
Labels: bug

#177 #176 Unit tests for subscription endpoints
  test/js/api/notify-info.js
  test/js/api/order.js
Labels: unit-testing

#180 Add logo
  README.md
  res/logo.png
  res/logo.svg
Labels: enhancement

#181 #504 Add get locale model keys
  src/js/api/build.js
Labels: enhancement

#182 Small fix
  res/logo.svg
  src/python/ripe_demo/static/images/logo-2x.png
  src/python/ripe_demo/static/images/logo.png
Labels: enhancement
