Repository ripe-tech/ripe-sdk, pull requests merged in 2021-02, with the labels that each got.

#238 fix: support initialsExtra with one group in _queryToSpec
  src/js/base/api.js
  test/js/base/api.js
Labels: bug, unit-testing

#236 #32: Order and related types
  package.json
  types/api/attachment.d.ts
  types/api/gender.d.ts
  types/api/index.d.ts
  types/api/order.d.ts
  types/base/api.d.ts
  types/base/index.d.ts
  types/index.d.ts
Labels: enhancement

#240 feat: localeModel
  src/js/base/logic.js
  src/js/base/utils.js
  test/js/base/utils.js
Labels: enhancement, risky ❕

#241 fix: FileTuple prototype fix
  src/js/base/struct.js
Labels: bug

#242 test: verify that the array constructor is not overriden by FileTuple
  test/js/base/struct.js
Labels: unit-testing

#243 fix: check if element is not defined in drawMask
  src/js/visual/configurator-prc.js
Labels: bug

#244 fix: tolerate no element on buildSignature
  src/js/visual/configurator-prc.js
Labels: bug

#245 #650: Save and later execute changeFrame operations while preloading
  src/js/visual/configurator-prc.js
Labels: bug

#247 #761 Add initials no radius status and test
  src/js/base/config.js
  src/js/visual/configurator-prc.js
  test/js/base/config.js
Labels: enhancement, unit-testing

#250 #768 Add size to setOptions
  src/js/api/brand.js
  src/js/api/config.js
  src/js/base/ripe.js
Labels: enhancement

#251 feat: add import order fields
  src/js/api/order.js
Labels: enhancement

#249 #641 Fix setting initialsExtra in root and options of ripe instance
  src/js/base/ripe.js
  src/js/visual/configurator-prc.js
Labels: bug

#253 feat: chat lines and attachments count endpoints
  src/js/api/order.js
Labels: enhancement

#254 feat: validate SKU endpoint
  src/js/api/sku.js
Labels: enhancement

#252 #44 Parts, color, materials and properties localization support
  src/js/base/logic.js
Labels: documentation, enhancement
