Repository ripe-tech/ripe-sdk, pull requests merged in 2021-07, with the labels that each got.

#287 feat: attachments meta and name
  CHANGELOG.md
  src/js/api/order.js
  src/js/base/api.js
  test/js/base/api.js
Labels: enhancement, talk

#288 #219 Adds rejectOrder and rejectOrderP methods
  CHANGELOG.md
  src/js/api/order.js
Labels: enhancement

#284 feat: create waybill for order
  CHANGELOG.md
  src/js/api/order.js
Labels: enhancement

#285 Fix: Override tracking info and keep other params
  CHANGELOG.md
  src/js/api/order.js
Labels: bug, p-medium

#289 version: 2.2.0
  CHANGELOG.md
  package.json
  src/js/base/ripe.js
Labels: enhancement

#290 fix: stateCreateAttachmentOrder regression
  CHANGELOG.md
  src/js/api/order.js
Labels: bug, regression

#291 version: 2.2.1
  CHANGELOG.md
  package.json
  src/js/base/ripe.js
Labels: enhancement

#292 #105 Get attachment URL
  CHANGELOG.md
  src/js/api/attachment.js
  src/js/api/index.js
  src/js/base/api.js
  test/js/api/attachment.js
Labels: enhancement

#293 version: 2.2.2
  CHANGELOG.md
  package.json
  src/js/base/ripe.js
Labels: enhancement

#294 fix: requires to comply with react-native
  src/js/base/compat.js
Labels: bug, regression

#295 version: 2.2.3
  CHANGELOG.md
  package.json
  src/js/base/ripe.js
Labels: enhancement

#296 feat: use option size in configurator resize
  CHANGELOG.md
  src/js/visual/configurator-prc.js
Labels: enhancement, risky ❕

#297 version: 2.3.0
  CHANGELOG.md
  package.json
  src/js/base/ripe.js
Labels: enhancement

#298 Feat: Add notes to order
  src/js/api/order.js
Labels: blocked ⛔, enhancement

#299 Fix: Remove email param from note creation
  src/js/api/order.js
Labels: bug
