Repository ripe-tech/ripe-sdk, pull requests merged in 2021-11, with the labels that each got.

#321 feat: use config animate if update is made after config
  src/js/visual/configurator-prc.js
Labels: bug

#326 #312: Suport size in mask image request
  CHANGELOG.md
  src/js/base/api.js
Labels: enhancement

#323 #263: `blockOrderP` to block an order
  CHANGELOG.md
  src/js/api/order.js
Labels: enhancement

#328 #260 Refresh shipping methods
  CHANGELOG.md
  src/js/api/order.js
Labels: enhancement

#327 feat: add `setReturnTracking`
  CHANGELOG.md
  src/js/api/order.js
Labels: enhancement

#325 feat: create return waybill method
  CHANGELOG.md
  src/js/api/order.js
Labels: enhancement

#330 feat: `setProofOfDelivery` method
  CHANGELOG.md
  src/js/api/order.js
Labels: enhancement

#332 Fix documentation
  src/js/api/config.js
  src/js/api/size.js
Labels: documentation

#333 test: fix brand getLogoP test
  test/js/api/brand.js
Labels: bug, unit-testing

#334 docs: add missing order methods documentation
  src/js/api/order.js
Labels: enhancement, documentation
