Repository ripe-tech/ripe-sdk, pull requests merged in 2021-01, with the labels that each got.

#231 docs: fix inconsistencies
  src/js/api/availability-rule.js
  src/js/api/brand.js
  src/js/api/country-group.js
  src/js/api/letter-rule.js
  src/js/api/notify-info.js
  src/js/api/price-rule.js
  src/js/base/logic.js
  src/js/base/ripe.js
Labels: documentation

#232 #730: SKUs methods
  src/js/api/sku.js
  test/js/api/sku.js
Labels: enhancement, unit-testing

#233 fix: stateChatCreateLineOrderP POST instead of GET
  src/js/api/order.js
Labels: bug

#235 #32: Type definitions
  package.json
  types/base/api.d.ts
  types/base/index.d.ts
  types/index.d.ts
Labels: enhancement

#234 fix: configurator cancel signature error
  src/js/visual/configurator-prc.js
  src/js/visual/image.js
Labels: bug, core 💎, risky ❕
