Repository ripe-tech/ripe-sdk, pull requests merged in 2021-08, with the labels that each got.

#300 version: 2.4.0
  CHANGELOG.md
  package.json
  src/js/base/ripe.js
Labels: enhancement

#301 fix: support null context on buildProfiles function
  src/js/base/ripe.js
  test/js/base/ripe.js
Labels: bug, unit-testing

#304 fix: add itertools file to basefiles
  CHANGELOG.md
  gulpfile.js
Labels: bug

#302 fix: sets default values for initials and engraving on image update
  src/js/base/compat.js
  src/js/visual/image.js
  test/js/visual.js
Labels: bug
