Repository ripe-tech/ripe-sdk, pull requests merged in 2022-04, with the labels that each got.

#385 feat: resolveJustification method
  CHANGELOG.md
  src/js/api/justification.js
Labels: enhancement

#378 YSL: Add `remoteInitialsBuilderLogic` option
  CHANGELOG.md
  src/js/base/ripe.js
  src/js/visual/image.js
Labels: fast-track, ysl

#387 version: 0.26.0
  CHANGELOG.md
  package.json
  src/js/base/ripe.js
Labels: release 🎉

#386 YSL: Passing compose `options` option
  CHANGELOG.md
  src/js/base/api.js
  src/js/visual/image.js
Labels: enhancement, ysl

#388 version: 2.27.0
  CHANGELOG.md
  package.json
  src/js/base/ripe.js
Labels: release 🎉

#389 version: 2.28.0
  CHANGELOG.md
  package.json
  src/js/base/ripe.js
Labels: release 🎉

#390 feat: set order tag and tag activation methods
  CHANGELOG.md
  src/js/api/order.js
Labels: enhancement, fast-track

#391 version: 2.29.0
  CHANGELOG.md
  package.json
  src/js/base/ripe.js
Labels: blocked ⛔, release 🎉
