Repository ripe-tech/ripe-sdk, pull requests merged in 2022-02, with the labels that each got.

#354 Initials builder ctx message dispatcher
  CHANGELOG.md
  src/js/visual/image.js
Labels: enhancement, fast-track

#355 feat: resolve invoice rule function
  CHANGELOG.md
  src/js/api/invoice-rule.js
Labels: enhancement

#335 #276: shipment API
  CHANGELOG.md
  src/js/api/index.js
  src/js/api/shipment.js
  test/js/api/shipment.js
Labels: enhancement

#361 fix: use same linting directories for prettier
  package.json
  src/js/api/order.js
Labels: bug

#359 #281: fix import bulk method
  CHANGELOG.md
  src/js/api/bulk-order.js
Labels: bug

#362 version: 2.21.0
  CHANGELOG.md
  package.json
  src/js/base/ripe.js
Labels: release 🎉
