Repository ripe-tech/ripe-sdk, pull requests merged in 2022-10, with the labels that each got.

#430 feat: import order simple methods
  CHANGELOG.md
  src/js/api/order.js
Labels: enhancement

#428 Reset CSR configurator zoom on PRC sync
  CHANGELOG.md
  src/js/visual/configurator-csr.js
Labels: enhancement

#431 Fix CSR debug mode not properly initializing when no CSR initials points are set
  CHANGELOG.md
  src/js/visual/configurator-csr.js
Labels: bug

#433 Fix changelog
  CHANGELOG.md
Labels: bug

#435 feat: info method endpoint
  CHANGELOG.md
  src/js/base/api.js
  test/js/base/api.js
Labels: enhancement, hacktoberfest-accepted

#434 #429 Remove external draco loader dependency
  CHANGELOG.md
  gulpfile.js
  src/js/visual/configurator-csr.js
  src/js/visual/csr/utils.js
Labels: enhancement

#436 test: add coverage
  .github/workflows/main.yml
  CHANGELOG.md
  gulpfile.js
  package.json
Labels: enhancement, unit-testing, hacktoberfest-accepted

#437 #429 [CSR] Add tone mapping
  CHANGELOG.md
  src/js/visual/configurator-csr.js
Labels: enhancement

#438 #429 [CSR] Fix debug line points boxes wrong size
  CHANGELOG.md
  src/js/visual/configurator-csr.js
Labels: bug

#440 #429 Add `toXYZObject`, `toVector3` and `toToneMappingValue` utils
  CHANGELOG.md
  src/js/visual/csr/utils.js
Labels: enhancement
