Repository ripe-tech/ripe-sdk, pull requests merged in 2022-05, with the labels that each got.

#393 #135 Add `fromArrayBuffer` and `fromBlob` to `FileTuple`
  CHANGELOG.md
  src/js/base/struct.js
  test/js/base/struct.js
Labels: enhancement, unit-testing

#394 #978: support profile overriding in image
  CHANGELOG.md
  src/js/visual/image.js
Labels: enhancement

#395 version: 2.30.0
  CHANGELOG.md
  package.json
  src/js/base/ripe.js
Labels: enhancement, release 🎉

#396 fix: eslint dependency problems
  .github/workflows/deploy.yml
  .github/workflows/main.yml
  CHANGELOG.md
  package.json
Labels: bug, back-port 🔮
