Repository ripe-tech/ripe-sdk, pull requests merged in 2022-11, with the labels that each got.

#442 #429 Increase number of curve types supported by `CsrRenderedInitials`
  CHANGELOG.md
  src/js/visual/configurator-csr.js
  src/js/visual/csr/rendered-initials.js
Labels: enhancement

#443 version: 2.32.0
  CHANGELOG.md
  package.json
Labels: enhancement, release 🎉

#444 fix: typo of useMasks
  src/js/visual/configurator-prc.js
Labels: bug

#447 fix: load mask only if using masks
  CHANGELOG.md
  src/js/visual/configurator-prc.js
Labels: bug, risky ❕
