Repository ripe-tech/ripe-sdk, pull requests merged in 2022-01, with the labels that each got.

#336 test: allow config core instance
  test/js/api/attachment.js
  test/js/api/brand.js
  test/js/api/config.js
  test/js/api/mock.js
  test/js/api/notify-info.js
  test/js/api/order.js
  test/js/api/profile.js
  test/js/api/size.js
  test/js/api/sku.js
  test/js/base/api.js
  test/js/base/auth.js
  test/js/config.js
  test/js/locales/base.js
  test/js/visual.js
Labels: enhancement, risky ❕, testing 👮

#337 #3: invoice rules API methods
  CHANGELOG.md
  src/js/api/index.js
  src/js/api/invoice-rule.js
Labels: enhancement

#338 feat: text length endpoint
  CHANGELOG.md
  src/js/api/brand.js
  src/js/base/ripe.js
  src/js/visual/image.js
  test/js/base/ripe.js
Labels: enhancement

#339 version: 2.12.0
  CHANGELOG.md
  package.json
  src/js/base/ripe.js
Labels: enhancement

#340 #943: configurator PRC support for width and height (non-square images)
  CHANGELOG.md
  src/js/visual/configurator-prc.js
Labels: enhancement, fast-track

#341 feat: added missing params to _getImageOptions
  CHANGELOG.md
  src/js/base/api.js
Labels: enhancement

#344 feat: support width and height in image resize
  CHANGELOG.md
  src/js/visual/image.js
Labels: enhancement

#346 #948: Use pixel ratio in image
  CHANGELOG.md
  src/js/visual/configurator-prc.js
  src/js/visual/image.js
Labels: bug

#348 fix: convert image size and width height to ints
  CHANGELOG.md
  src/js/visual/image.js
Labels: bug, fast-track

#347 fix: move usePixelRatio logic to image instead of configurator
  src/js/visual/configurator-prc.js
  src/js/visual/image.js
Labels: bug, no-changelog

#349 fix: remove default width and height for configurator
  CHANGELOG.md
  src/js/visual/configurator-prc.js
Labels: bug

#350 feat: line break endpoint API methods
  CHANGELOG.md
  src/js/api/brand.js
Labels: enhancement

#352 version: 2.17.0
  CHANGELOG.md
  package.json
  src/js/base/ripe.js
Labels: bug, fast-track

#353 feat: setPickupNumber for Order API
  CHANGELOG.md
  src/js/api/order.js
Labels: enhancement
