Repository ripe-tech/ripe-sdk, pull requests merged in 2022-03, with the labels that each got.

#358 fix: use locked dimensions for configurator (the face default) and apply DPR
  CHANGELOG.md
  src/js/visual/configurator-prc.js
Labels: bug

#367 feat: void waybills
  CHANGELOG.md
  src/js/api/order.js
Labels: enhancement

#369 version: 2.23.0
  CHANGELOG.md
  package.json
  src/js/base/ripe.js
Labels: release 🎉

#370 #979: Methods `getSkusCsvP` and `countSkusP`
  CHANGELOG.md
  src/js/api/sku.js
Labels: enhancement

#371 fix: optional brand in payload
  CHANGELOG.md
  src/js/api/bulk-order.js
Labels: bug

#366 #363 YSL: Improve update cancellation strategy
  CHANGELOG.md
  src/js/visual/image.js
Labels: enhancement, fast-track, ysl

#372 version: 2.24.0
  CHANGELOG.md
  package.json
  src/js/base/ripe.js
Labels: release 🎉

#324 #923 Add default locale bundle initialization
  CHANGELOG.md
  src/js/base/ripe.js
Labels: bug, fast-track

#373 #4703 Add size to rules
  CHANGELOG.md
  src/js/api/invoice-rule.js
  src/js/api/transport-rule.js
Labels: enhancement, blocked ⛔

#375 #966: Methods to return a video and video thumbnail image
  CHANGELOG.md
  src/js/base/api.js
Labels: enhancement

#376 #4702: General order chat methods
  CHANGELOG.md
  src/js/api/order.js
Labels: enhancement

#377 #966: Image support for external image providers/frame validators
  CHANGELOG.md
  src/js/base/logic.js
  src/js/base/ripe.js
  src/js/visual/image.js
Labels: enhancement

#379 fix: no faces in dimension spec in `getDimension`
  CHANGELOG.md
  src/js/base/ripe.js
Labels: bug

#383 #381 Fix `_getOrderReportURL`, `_getOrderReportPDFURL`, `_getOrderReportPNGURL` logic and tests
  CHANGELOG.md
  src/js/api/order.js
  test/js/api/order.js
Labels: bug, unit-testing
