Repository ripe-tech/ripe-sdk, pull requests merged in 2022-06, with the labels that each got.

#397 feat: delete and deactivate order tags
  CHANGELOG.md
  src/js/api/order.js
Labels: enhancement

#399 fix: initialsSpec profile spread fallback value in image
  CHANGELOG.md
  src/js/visual/image.js
Labels: bug

#400 version: 2.31.1
  CHANGELOG.md
  package.json
  src/js/base/ripe.js
Labels: release 🎉

#401 #363 Tag: Add param `tenent_id`
  CHANGELOG.md
  src/js/api/order.js
Labels: enhancement
