Repository ripe-tech/ripe-sdk, pull requests merged in 2023-01, with the labels that each got.

#456 #429 Increase control points debug boxes size
  CHANGELOG.md
  src/js/visual/configurator-csr.js
Labels: bug

#458 fix: change order status options
  CHANGELOG.md
  src/js/api/order.js
Labels: bug

#459 version: 2.34.0
  CHANGELOG.md
  package.json
  src/js/base/ripe.js
Labels: release 🎉

#460 feat: endpoints to create order issues
  CHANGELOG.md
  src/js/api/order.js
Labels: enhancement

#461 version: 2.35.0
  CHANGELOG.md
  package.json
  src/js/base/ripe.js
  src/js/visual/csr/utils.js
Labels: release 🎉

#464 #340 Chat Lines: small fix reference method
  CHANGELOG.md
  src/js/api/order.js
Labels: bug

#465 version 2.35.1 :rainbow:
  CHANGELOG.md
  package.json
  src/js/base/ripe.js
Labels: release 🎉

#467 #466 Fix test race condition
  test/js/api/config.js
Labels: bug, no-changelog

#468 #4778 Fix tests
  CHANGELOG.md
  src/js/api/order.js
  test/js/api/order.js
Labels: bug, enhancement

#454 #429 Support metallic, normal and roughness textures
  CHANGELOG.md
  src/js/api/brand.js
  src/js/visual/configurator-csr.js
  src/js/visual/csr/rendered-initials.js
Labels: enhancement

#470 style: pretty
  src/js/api/order.js
Labels: enhancement

#469 #429 Support post render callback
  CHANGELOG.md
  src/js/visual/configurator-csr.js
Labels: enhancement

#472 feat: apk add alpine enhancement
  Dockerfile
  Dockerfile.demo
  Dockerfile.docs
Labels: enhancement, no-changelog
