Repository ripe-tech/ripe-sdk, pull requests merged in 2023-02, with the labels that each got.

#471 #416 Auth callback
  CHANGELOG.md
  src/js/base/api.js
  src/js/base/ripe.js
Labels: enhancement

#473 #429 Use enriched initials config
  CHANGELOG.md
  src/js/api/brand.js
  src/js/visual/configurator-csr.js
Labels: enhancement

#455 #429 Use texture_maps endpoint
  CHANGELOG.md
  src/js/api/brand.js
  src/js/visual/configurator-csr.js
Labels: enhancement

#463 #429 Support loading of external fonts
  CHANGELOG.md
  src/js/api/brand.js
  src/js/visual/configurator-csr.js
Labels: enhancement

#474 version 2.36.0 :rainbow:
  CHANGELOG.md
  package.json
  src/js/base/ripe.js
Labels: release 🎉

#475 #429 Update CSR initials config loading
  CHANGELOG.md
  src/js/visual/configurator-csr.js
  src/js/visual/csr/utils.js
Labels: enhancement

#480 Version: `2.37.0`
  CHANGELOG.md
  package.json
  src/js/base/ripe.js
Labels: release 🎉

#483 #481 Fix meshes compressed with Draco not loading properly
  CHANGELOG.md
  gulpfile.js
  src/js/visual/configurator-csr.js
  src/js/visual/csr/utils.js
Labels: bug, enhancement, CSR

#484 #1098 Add params to `ready` event in configurator csr and prc
  CHANGELOG.md
  src/js/visual/configurator-csr.js
  src/js/visual/configurator-prc.js
Labels: enhancement

#485 #479 Support computation of initials config by adding `initialsConfig` method
  CHANGELOG.md
  src/js/base/config.js
  test/js/base/config.js
Labels: enhancement, unit-testing

#487 Version: `2.38.0`
  CHANGELOG.md
  package.json
  src/js/base/ripe.js
Labels: release 🎉

#488 #1098 Allow basic set initials extra
  CHANGELOG.md
  src/js/visual/configurator-csr.js
Labels: enhancement, CSR

#489 version: 2.39.0 :rainbow:
  CHANGELOG.md
  package.json
  src/js/base/ripe.js
Labels: release 🎉
