Repository ripe-tech/ripe-sdk, pull requests merged in 2023-03, with the labels that each got.

#492 #478 Add CSR alt documentation
  CHANGELOG.md
  documentation/package.json
  documentation/src/README.md
  documentation/src/config.js
  documentation/src/public/images/logo.svg
  documentation/src/styles/index.scss
  documentation/vercel.json
Labels: enhancement

#490 #429 Update `_initialsMerge` to match remote logic
  CHANGELOG.md
  src/js/base/config.js
  test/js/base/config.js
Labels: enhancement

#496 #478 Fix CSR documentation compilation
  .gitignore
  CHANGELOG.md
  documentation/src/README.md
Labels: documentation

#501 version 2.40.0 :rainbow:
  CHANGELOG.md
  package.json
  src/js/base/ripe.js
Labels: release 🎉

#500 #499 Load environment file bases on config
  CHANGELOG.md
  src/js/api/brand.js
  src/js/visual/configurator-csr.js
Labels: enhancement, CSR

#495 #491 Update Three.js version and RIPE-SDK's bundler
  .gitignore
  CHANGELOG.md
  gulpfile.js
  package.json
  src/js/api/account.js
  src/js/api/attachment.js
  src/js/api/availability-rule.js
  src/js/api/brand.js
  src/js/api/build.js
  src/js/api/bulk-order.js
  src/js/api/config.js
  src/js/api/country-group.js
  src/js/api/factory-rule.js
  src/js/api/invoice-rule.js
  src/js/api/justification.js
  src/js/api/letter-rule.js
  src/js/api/locale.js
  src/js/api/notify-info.js
  src/js/api/oauth.js
  src/js/api/order.js
  src/js/api/price-rule.js
  src/js/api/profile.js
  src/js/api/shipment.js
  src/js/api/size.js
  src/js/api/sku.js
  src/js/api/transport-rule.js
  src/js/base/api.js
  src/js/base/auth.js
  src/js/base/base.js
  src/js/base/compat.js
  src/js/base/config.js
  src/js/base/errors.js
  src/js/base/interactable.js
  src/js/base/itertools.js
  src/js/base/logic.js
  src/js/base/mobile.js
  src/js/base/observable.js
  src/js/base/ripe.js
  src/js/base/struct.js
  src/js/base/utils.js
  src/js/index.mjs
  src/js/locales/base.js
  src/js/plugins/base.js
  src/js/plugins/diag.js
  src/js/plugins/restrictions.js
  src/js/plugins/sync.js
  src/js/visual/configurator-csr.js
  src/js/visual/configurator-prc.js
  src/js/visual/csr/animation-base.js
  src/js/visual/csr/animation-change-frame.js
  src/js/visual/csr/rendered-initials.js
  src/js/visual/csr/texture-renderer.js
  src/js/visual/csr/utils.js
  src/js/visual/image.js
  src/js/visual/visual.js
  src/python/ripe_demo/templates/partials/layout.html.tpl
Labels: enhancement, risky ❕, CSR

#503 Version: `3.0.0`
  CHANGELOG.md
  package.json
  src/js/base/ripe.js
Labels: release 🎉

#504 Add date to changelong
  CHANGELOG.md
Labels: enhancement
